/* Automatically generated by wasm2c */
#ifndef APLTYPED_GROK_WASM_H_GENERATED_
#define APLTYPED_GROK_WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_apltyped0x2Egrok {
  u32 w2c_g0;
  u32 w2c_g1;
  wasm_rt_memory_t w2c_memory;
} w2c_apltyped0x2Egrok;

void wasm2c_apltyped0x2Egrok_instantiate(w2c_apltyped0x2Egrok*);
void wasm2c_apltyped0x2Egrok_free(w2c_apltyped0x2Egrok*);
wasm_rt_func_type_t wasm2c_apltyped0x2Egrok_get_func_type(uint32_t param_count, uint32_t result_count, ...);

#ifndef wasm_multi_iii
#define wasm_multi_iii wasm_multi_iii
struct wasm_multi_iii {
  u32 i0;
  u32 i1;
  u32 i2;
};
#endif  /* wasm_multi_iii */

/* export: 'memory' */
wasm_rt_memory_t* w2c_apltyped0x2Egrok_memory(w2c_apltyped0x2Egrok* instance);

/* export: 'main' */
struct wasm_multi_iii w2c_apltyped0x2Egrok_main(w2c_apltyped0x2Egrok*, u32, u32);

/* export: 'reset_heap' */
void w2c_apltyped0x2Egrok_reset_heap(w2c_apltyped0x2Egrok*);

/* export: 'deal' */
u32 w2c_apltyped0x2Egrok_deal(w2c_apltyped0x2Egrok*, u32, u32);

/* export: 'indexGenerator' */
u32 w2c_apltyped0x2Egrok_indexGenerator(w2c_apltyped0x2Egrok*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* APLTYPED_GROK_WASM_H_GENERATED_ */
