/* Automatically generated by wasm2c */
#include <assert.h>
#include <math.h>
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#if defined(__MINGW32__)
#include <malloc.h>
#elif defined(_MSC_VER)
#include <intrin.h>
#include <malloc.h>
#define alloca _alloca
#elif defined(__FreeBSD__) || defined(__OpenBSD__)
#include <stdlib.h>
#else
#include <alloca.h>
#endif

#include "apltyped.grok.wasm.h"
#define IS_SINGLE_UNSHARED_MEMORY 1

// Computes a pointer to an object of the given size in a little-endian memory.
//
// On a little-endian host, this is just &mem->data[addr] - the object's size is
// unused. On a big-endian host, it's &mem->data[mem->size - addr - n], where n
// is the object's size.
//
// Note that mem may be evaluated multiple times.
//
// Parameters:
// mem - The memory.
// addr - The address.
// n - The size of the object.
//
// Result:
// A pointer for an object of size n.
#if WABT_BIG_ENDIAN
#define MEM_ADDR(mem, addr, n) &(mem)->data[(mem)->size - (addr) - (n)]
#else
#define MEM_ADDR(mem, addr, n) &(mem)->data[addr]
#endif

// We can only use Segue for this module if it uses a single unshared imported
// or exported memory
#if WASM_RT_USE_SEGUE && IS_SINGLE_UNSHARED_MEMORY
#define WASM_RT_USE_SEGUE_FOR_THIS_MODULE 1
#else
#define WASM_RT_USE_SEGUE_FOR_THIS_MODULE 0
#endif

#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
// POSIX uses FS for TLS, GS is free
static inline void* wasm_rt_segue_read_base() {
  if (wasm_rt_fsgsbase_inst_supported) {
    return (void*)__builtin_ia32_rdgsbase64();
  } else {
    return wasm_rt_syscall_get_segue_base();
  }
}
static inline void wasm_rt_segue_write_base(void* base) {
#if WASM_RT_SEGUE_FREE_SEGMENT
  if (wasm_rt_last_segment_val == base) {
    return;
  }

  wasm_rt_last_segment_val = base;
#endif

  if (wasm_rt_fsgsbase_inst_supported) {
    __builtin_ia32_wrgsbase64((uintptr_t)base);
  } else {
    wasm_rt_syscall_set_segue_base(base);
  }
}
#define MEM_ADDR_MEMOP(mem, addr, n) ((uint8_t __seg_gs*)(uintptr_t)addr)
#else
#define MEM_ADDR_MEMOP(mem, addr, n) MEM_ADDR(mem, addr, n)
#endif

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#if WASM_RT_STACK_DEPTH_COUNT
#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION);

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth
#else
#define FUNC_PROLOGUE

#define FUNC_EPILOGUE
#endif

#define UNREACHABLE TRAP(UNREACHABLE)

static inline bool func_types_eq(const wasm_rt_func_type_t a,
                                 const wasm_rt_func_type_t b) {
  return (a == b) || LIKELY(a && b && !memcmp(a, b, 32));
}

#define CHECK_CALL_INDIRECT(table, ft, x)                \
  (LIKELY((x) < table.size && table.data[x].func &&      \
          func_types_eq(ft, table.data[x].func_type)) || \
   TRAP(CALL_INDIRECT))

#define DO_CALL_INDIRECT(table, t, x, ...) ((t)table.data[x].func)(__VA_ARGS__)

#define CALL_INDIRECT(table, t, ft, x, ...) \
  (CHECK_CALL_INDIRECT(table, ft, x),       \
   DO_CALL_INDIRECT(table, t, x, __VA_ARGS__))

static inline bool add_overflow(uint64_t a, uint64_t b, uint64_t* resptr) {
#if __has_builtin(__builtin_add_overflow)
  return __builtin_add_overflow(a, b, resptr);
#elif defined(_MSC_VER)
  return _addcarry_u64(0, a, b, resptr);
#else
#error "Missing implementation of __builtin_add_overflow or _addcarry_u64"
#endif
}

#define RANGE_CHECK(mem, offset, len)              \
  do {                                             \
    uint64_t res;                                  \
    if (UNLIKELY(add_overflow(offset, len, &res))) \
      TRAP(OOB);                                   \
    if (UNLIKELY(res > mem->size))                 \
      TRAP(OOB);                                   \
  } while (0);

#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && WASM_RT_SANITY_CHECKS
#include <stdio.h>
#define WASM_RT_CHECK_BASE(mem)                                               \
  if (((uintptr_t)((mem)->data)) != ((uintptr_t)wasm_rt_segue_read_base())) { \
    puts("Segment register mismatch\n");                                      \
    abort();                                                                  \
  }
#else
#define WASM_RT_CHECK_BASE(mem)
#endif

// MEMCHECK_DEFAULT32 is an "accelerated" MEMCHECK used only for
// default-page-size, 32-bit memories. It may do nothing at all
// (if hardware bounds-checking is enabled via guard pages)
// or it may do a slightly faster RANGE_CHECK.
#if WASM_RT_MEMCHECK_GUARD_PAGES
#define MEMCHECK_DEFAULT32(mem, a, t) WASM_RT_CHECK_BASE(mem);
#else
#define MEMCHECK_DEFAULT32(mem, a, t)                \
  WASM_RT_CHECK_BASE(mem);                           \
  if (UNLIKELY(a + (uint64_t)sizeof(t) > mem->size)) \
    TRAP(OOB);
#endif

// MEMCHECK_GENERAL can be used for any memory
#define MEMCHECK_GENERAL(mem, a, t) \
  WASM_RT_CHECK_BASE(mem);          \
  RANGE_CHECK(mem, a, sizeof(t));

#ifdef __GNUC__
#define FORCE_READ_INT(var) __asm__("" ::"r"(var));
// Clang on Mips requires "f" constraints on floats
// See https://github.com/llvm/llvm-project/issues/64241
#if defined(__clang__) && \
    (defined(mips) || defined(__mips__) || defined(__mips))
#define FORCE_READ_FLOAT(var) __asm__("" ::"f"(var));
#else
#define FORCE_READ_FLOAT(var) __asm__("" ::"r"(var));
#endif
#else
#define FORCE_READ_INT(var)
#define FORCE_READ_FLOAT(var)
#endif

static inline void load_data(void* dest, const void* src, size_t n) {
  if (!n) {
    return;
  }
  wasm_rt_memcpy(dest, src, n);
#if WABT_BIG_ENDIAN
  u8* dest_chars = dest;
  for (size_t i = 0; i < (n >> 1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
#endif
}

#define LOAD_DATA(m, o, i, s)            \
  do {                                   \
    RANGE_CHECK((&m), o, s);             \
    load_data(MEM_ADDR(&m, o, s), i, s); \
  } while (0)

#define DEF_MEM_CHECKS0(name, shared, mem_type, ret_kw, return_type)         \
  static inline return_type name##_default32(wasm_rt##shared##memory_t* mem, \
                                             u64 addr) {                     \
    MEMCHECK_DEFAULT32(mem, addr, mem_type);                                 \
    ret_kw name##_unchecked(mem, addr);                                      \
  }                                                                          \
  static inline return_type name(wasm_rt##shared##memory_t* mem, u64 addr) { \
    MEMCHECK_GENERAL(mem, addr, mem_type);                                   \
    ret_kw name##_unchecked(mem, addr);                                      \
  }

#define DEF_MEM_CHECKS1(name, shared, mem_type, ret_kw, return_type,         \
                        val_type1)                                           \
  static inline return_type name##_default32(wasm_rt##shared##memory_t* mem, \
                                             u64 addr, val_type1 val1) {     \
    MEMCHECK_DEFAULT32(mem, addr, mem_type);                                 \
    ret_kw name##_unchecked(mem, addr, val1);                                \
  }                                                                          \
  static inline return_type name(wasm_rt##shared##memory_t* mem, u64 addr,   \
                                 val_type1 val1) {                           \
    MEMCHECK_GENERAL(mem, addr, mem_type);                                   \
    ret_kw name##_unchecked(mem, addr, val1);                                \
  }

#define DEF_MEM_CHECKS2(name, shared, mem_type, ret_kw, return_type,         \
                        val_type1, val_type2)                                \
  static inline return_type name##_default32(wasm_rt##shared##memory_t* mem, \
                                             u64 addr, val_type1 val1,       \
                                             val_type2 val2) {               \
    MEMCHECK_DEFAULT32(mem, addr, mem_type);                                 \
    ret_kw name##_unchecked(mem, addr, val1, val2);                          \
  }                                                                          \
  static inline return_type name(wasm_rt##shared##memory_t* mem, u64 addr,   \
                                 val_type1 val1, val_type2 val2) {           \
    MEMCHECK_GENERAL(mem, addr, mem_type);                                   \
    ret_kw name##_unchecked(mem, addr, val1, val2);                          \
  }

#define DEFINE_LOAD(name, t1, t2, t3, force_read)                      \
  static inline t3 name##_unchecked(wasm_rt_memory_t* mem, u64 addr) { \
    t1 result;                                                         \
    wasm_rt_memcpy(&result, MEM_ADDR_MEMOP(mem, addr, sizeof(t1)),     \
                   sizeof(t1));                                        \
    force_read(result);                                                \
    return (t3)(t2)result;                                             \
  }                                                                    \
  DEF_MEM_CHECKS0(name, _, t1, return, t3)

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name##_unchecked(wasm_rt_memory_t* mem, u64 addr, \
                                      t2 value) {                      \
    t1 wrapped = (t1)value;                                            \
    wasm_rt_memcpy(MEM_ADDR_MEMOP(mem, addr, sizeof(t1)), &wrapped,    \
                   sizeof(t1));                                        \
  }                                                                    \
  DEF_MEM_CHECKS1(name, _, t1, , void, t2)

DEFINE_LOAD(i32_load, u32, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load, u64, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(f32_load, f32, f32, f32, FORCE_READ_FLOAT)
DEFINE_LOAD(f64_load, f64, f64, f64, FORCE_READ_FLOAT)
DEFINE_LOAD(i32_load8_s, s8, s32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load8_s, s8, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load8_u, u8, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load8_u, u8, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load16_s, s16, s32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load16_s, s16, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load16_u, u16, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load16_u, u16, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(i64_load32_s, s32, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i64_load32_u, u32, u64, u64, FORCE_READ_INT)
DEFINE_STORE(i32_store, u32, u32)
DEFINE_STORE(i64_store, u64, u64)
DEFINE_STORE(f32_store, f32, f32)
DEFINE_STORE(f64_store, f64, f64)
DEFINE_STORE(i32_store8, u8, u32)
DEFINE_STORE(i32_store16, u16, u32)
DEFINE_STORE(i64_store8, u8, u64)
DEFINE_STORE(i64_store16, u16, u64)
DEFINE_STORE(i64_store32, u32, u64)

#if defined(_MSC_VER)

// Adapted from
// https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h

static inline int I64_CLZ(unsigned long long v) {
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  if (_BitScanReverse64(&r, v)) {
    return 63 - r;
  }
#else
  if (_BitScanReverse(&r, (unsigned long)(v >> 32))) {
    return 31 - r;
  } else if (_BitScanReverse(&r, (unsigned long)v)) {
    return 63 - r;
  }
#endif
  return 64;
}

static inline int I32_CLZ(unsigned long v) {
  unsigned long r = 0;
  if (_BitScanReverse(&r, v)) {
    return 31 - r;
  }
  return 32;
}

static inline int I64_CTZ(unsigned long long v) {
  if (!v) {
    return 64;
  }
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  _BitScanForward64(&r, v);
  return (int)r;
#else
  if (_BitScanForward(&r, (unsigned int)(v))) {
    return (int)(r);
  }

  _BitScanForward(&r, (unsigned int)(v >> 32));
  return (int)(r + 32);
#endif
}

static inline int I32_CTZ(unsigned long v) {
  if (!v) {
    return 32;
  }
  unsigned long r = 0;
  _BitScanForward(&r, v);
  return (int)r;
}

#define POPCOUNT_DEFINE_PORTABLE(f_n, T)                            \
  static inline u32 f_n(T x) {                                      \
    x = x - ((x >> 1) & (T) ~(T)0 / 3);                             \
    x = (x & (T) ~(T)0 / 15 * 3) + ((x >> 2) & (T) ~(T)0 / 15 * 3); \
    x = (x + (x >> 4)) & (T) ~(T)0 / 255 * 15;                      \
    return (T)(x * ((T) ~(T)0 / 255)) >> (sizeof(T) - 1) * 8;       \
  }

POPCOUNT_DEFINE_PORTABLE(I32_POPCNT, u32)
POPCOUNT_DEFINE_PORTABLE(I64_POPCNT, u64)

#undef POPCOUNT_DEFINE_PORTABLE

#else

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#endif

#define DIV_S(ut, min, x, y)                                      \
  ((UNLIKELY((y) == 0))                                           \
       ? TRAP(DIV_BY_ZERO)                                        \
       : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
                                             : (ut)((x) / (y)))

#define REM_S(ut, min, x, y) \
  ((UNLIKELY((y) == 0))      \
       ? TRAP(DIV_BY_ZERO)   \
       : (UNLIKELY((x) == min && (y) == -1)) ? 0 : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x)op(y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                                     \
  ((UNLIKELY((x) != (x)))                                              \
       ? NAN                                                           \
       : (UNLIKELY((y) != (y)))                                        \
             ? NAN                                                     \
             : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
                                                : (x < y) ? x : y)

#define FMAX(x, y)                                                     \
  ((UNLIKELY((x) != (x)))                                              \
       ? NAN                                                           \
       : (UNLIKELY((y) != (y)))                                        \
             ? NAN                                                     \
             : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
                                                : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                           \
  ((UNLIKELY((x) != (x)))                                                 \
       ? TRAP(INVALID_CONVERSION)                                         \
       : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW) \
                                                     : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) \
  TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) \
  TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) \
  TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) \
  TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                          \
  ((UNLIKELY((x) != (x)))                                                \
       ? TRAP(INVALID_CONVERSION)                                        \
       : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW) \
                                                    : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296., x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))                                       \
       ? 0                                                      \
       : (UNLIKELY(!((x)minop(min))))                           \
             ? smin                                             \
             : (UNLIKELY(!((x) < (max)))) ? smax : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F32(x)                                            \
  TRUNC_SAT_S(u32, s32, f32, (f32)INT32_MIN, INT32_MIN, >=, 2147483648.f, \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F32(x)                                              \
  TRUNC_SAT_S(u64, s64, f32, (f32)INT64_MIN, INT64_MIN, >=, (f32)INT64_MAX, \
              INT64_MAX, x)
#define I32_TRUNC_SAT_S_F64(x)                                        \
  TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F64(x)                                              \
  TRUNC_SAT_S(u64, s64, f64, (f64)INT64_MIN, INT64_MIN, >=, (f64)INT64_MAX, \
              INT64_MAX, x)

#define TRUNC_SAT_U(ut, ft, max, smax, x)               \
  ((UNLIKELY((x) != (x))) ? 0                           \
                          : (UNLIKELY(!((x) > (ft)-1))) \
                                ? 0                     \
                                : (UNLIKELY(!((x) < (max)))) ? smax : (ut)(x))

#define I32_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u32, f32, 4294967296.f, UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u64, f32, (f32)UINT64_MAX, UINT64_MAX, x)
#define I32_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u32, f64, 4294967296., UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F64(x) \
  TRUNC_SAT_U(u64, f64, (f64)UINT64_MAX, UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)         \
  static inline t2 name(t1 x) {                  \
    t2 result;                                   \
    wasm_rt_memcpy(&result, &x, sizeof(result)); \
    return result;                               \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)

static float quiet_nanf(float x) {
  uint32_t tmp;
  wasm_rt_memcpy(&tmp, &x, 4);
  tmp |= 0x7fc00000lu;
  wasm_rt_memcpy(&x, &tmp, 4);
  return x;
}

static double quiet_nan(double x) {
  uint64_t tmp;
  wasm_rt_memcpy(&tmp, &x, 8);
  tmp |= 0x7ff8000000000000llu;
  wasm_rt_memcpy(&x, &tmp, 8);
  return x;
}

static double wasm_quiet(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return x;
}

static float wasm_quietf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return x;
}

static double wasm_floor(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return floor(x);
}

static float wasm_floorf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return floorf(x);
}

static double wasm_ceil(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return ceil(x);
}

static float wasm_ceilf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return ceilf(x);
}

static double wasm_trunc(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return trunc(x);
}

static float wasm_truncf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return truncf(x);
}

static float wasm_nearbyintf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return nearbyintf(x);
}

static double wasm_nearbyint(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return nearbyint(x);
}

static float wasm_fabsf(float x) {
  if (UNLIKELY(isnan(x))) {
    uint32_t tmp;
    wasm_rt_memcpy(&tmp, &x, 4);
    tmp = tmp & ~(1UL << 31);
    wasm_rt_memcpy(&x, &tmp, 4);
    return x;
  }
  return fabsf(x);
}

static double wasm_fabs(double x) {
  if (UNLIKELY(isnan(x))) {
    uint64_t tmp;
    wasm_rt_memcpy(&tmp, &x, 8);
    tmp = tmp & ~(1ULL << 63);
    wasm_rt_memcpy(&x, &tmp, 8);
    return x;
  }
  return fabs(x);
}

static double wasm_sqrt(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return sqrt(x);
}

static float wasm_sqrtf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return sqrtf(x);
}

static inline void memory_fill(wasm_rt_memory_t* mem, u64 d, u32 val, u64 n) {
  RANGE_CHECK(mem, d, n);
  memset(MEM_ADDR(mem, d, n), val, n);
}

static inline void memory_copy(wasm_rt_memory_t* dest,
                               const wasm_rt_memory_t* src,
                               u64 dest_addr,
                               u64 src_addr,
                               u64 n) {
  RANGE_CHECK(dest, dest_addr, n);
  RANGE_CHECK(src, src_addr, n);
  memmove(MEM_ADDR(dest, dest_addr, n), MEM_ADDR(src, src_addr, n), n);
}

static inline void memory_init(wasm_rt_memory_t* dest,
                               const u8* src,
                               u32 src_size,
                               u64 dest_addr,
                               u32 src_addr,
                               u32 n) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  LOAD_DATA((*dest), dest_addr, src + src_addr, n);
}

typedef struct {
  enum { RefFunc, RefNull, GlobalGet } expr_type;
  wasm_rt_func_type_t type;
  wasm_rt_function_ptr_t func;
  wasm_rt_tailcallee_t func_tailcallee;
  size_t module_offset;
} wasm_elem_segment_expr_t;

static inline void funcref_table_init(wasm_rt_funcref_table_t* dest,
                                      const wasm_elem_segment_expr_t* src,
                                      u32 src_size,
                                      u64 dest_addr,
                                      u32 src_addr,
                                      u32 n,
                                      void* module_instance) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  RANGE_CHECK(dest, dest_addr, n);
  for (u32 i = 0; i < n; i++) {
    const wasm_elem_segment_expr_t* const src_expr = &src[src_addr + i];
    wasm_rt_funcref_t* const dest_val = &(dest->data[dest_addr + i]);
    switch (src_expr->expr_type) {
      case RefFunc:
        *dest_val = (wasm_rt_funcref_t){
            src_expr->type, src_expr->func, src_expr->func_tailcallee,
            (char*)module_instance + src_expr->module_offset};
        break;
      case RefNull:
        *dest_val = wasm_rt_funcref_null_value;
        break;
      case GlobalGet:
        *dest_val = **(wasm_rt_funcref_t**)((char*)module_instance +
                                            src_expr->module_offset);
        break;
    }
  }
}

// Currently wasm2c only supports initializing externref tables with ref.null.
static inline void externref_table_init(wasm_rt_externref_table_t* dest,
                                        u32 src_size,
                                        u64 dest_addr,
                                        u32 src_addr,
                                        u32 n) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  RANGE_CHECK(dest, dest_addr, n);
  for (u32 i = 0; i < n; i++) {
    dest->data[dest_addr + i] = wasm_rt_externref_null_value;
  }
}

#define DEFINE_TABLE_COPY(type)                                              \
  static inline void type##_table_copy(wasm_rt_##type##_table_t* dest,       \
                                       const wasm_rt_##type##_table_t* src,  \
                                       u64 dest_addr, u64 src_addr, u64 n) { \
    RANGE_CHECK(dest, dest_addr, n);                                         \
    RANGE_CHECK(src, src_addr, n);                                           \
    memmove(dest->data + dest_addr, src->data + src_addr,                    \
            n * sizeof(wasm_rt_##type##_t));                                 \
  }

DEFINE_TABLE_COPY(funcref)
DEFINE_TABLE_COPY(externref)

#define DEFINE_TABLE_GET(type)                        \
  static inline wasm_rt_##type##_t type##_table_get(  \
      const wasm_rt_##type##_table_t* table, u64 i) { \
    if (UNLIKELY(i >= table->size))                   \
      TRAP(OOB);                                      \
    return table->data[i];                            \
  }

DEFINE_TABLE_GET(funcref)
DEFINE_TABLE_GET(externref)

#define DEFINE_TABLE_SET(type)                                               \
  static inline void type##_table_set(const wasm_rt_##type##_table_t* table, \
                                      u64 i, const wasm_rt_##type##_t val) { \
    if (UNLIKELY(i >= table->size))                                          \
      TRAP(OOB);                                                             \
    table->data[i] = val;                                                    \
  }

DEFINE_TABLE_SET(funcref)
DEFINE_TABLE_SET(externref)

#define DEFINE_TABLE_FILL(type)                                               \
  static inline void type##_table_fill(const wasm_rt_##type##_table_t* table, \
                                       u64 d, const wasm_rt_##type##_t val,   \
                                       u64 n) {                               \
    RANGE_CHECK(table, d, n);                                                 \
    for (uint32_t i = d; i < d + n; i++) {                                    \
      table->data[i] = val;                                                   \
    }                                                                         \
  }

DEFINE_TABLE_FILL(funcref)
DEFINE_TABLE_FILL(externref)

#if defined(__GNUC__) || defined(__clang__)
#define FUNC_TYPE_DECL_EXTERN_T(x) extern const char* const x
#define FUNC_TYPE_EXTERN_T(x) const char* const x
#define FUNC_TYPE_T(x) static const char* const x
#else
#define FUNC_TYPE_DECL_EXTERN_T(x) extern const char x[]
#define FUNC_TYPE_EXTERN_T(x) const char x[]
#define FUNC_TYPE_T(x) static const char x[]
#endif

#if (__STDC_VERSION__ < 201112L) && !defined(static_assert)
#define static_assert(X) \
  extern int(*assertion(void))[!!sizeof(struct { int x : (X) ? 2 : -1; })];
#endif

#ifdef _MSC_VER
#define WEAK_FUNC_DECL(func, fallback)                             \
  __pragma(comment(linker, "/alternatename:" #func "=" #fallback)) \
                                                                   \
      void                                                         \
      fallback(void** instance_ptr, void* tail_call_stack,         \
               wasm_rt_tailcallee_t* next)
#else
#define WEAK_FUNC_DECL(func, fallback)                                        \
  __attribute__((weak)) void func(void** instance_ptr, void* tail_call_stack, \
                                  wasm_rt_tailcallee_t* next)
#endif

static u32 w2c_apltyped0x2Egrok_f0(w2c_apltyped0x2Egrok*, u32);
static u32 w2c_apltyped0x2Egrok_f1(w2c_apltyped0x2Egrok*);
static u32 w2c_apltyped0x2Egrok_indexGenerator_0(w2c_apltyped0x2Egrok*, u32);
static void w2c_apltyped0x2Egrok_f3(w2c_apltyped0x2Egrok*, u32, u32, u32, u32);
static u32 w2c_apltyped0x2Egrok_deal_0(w2c_apltyped0x2Egrok*, u32, u32);
static struct wasm_multi_iii w2c_apltyped0x2Egrok_main_0(w2c_apltyped0x2Egrok*, u32, u32);
static void w2c_apltyped0x2Egrok_reset_heap_0(w2c_apltyped0x2Egrok*);

FUNC_TYPE_T(w2c_apltyped0x2Egrok_t0) = "\x07\x80\x96\x7a\x42\xf7\x3e\xe6\x70\x5c\x2f\xac\x83\xf5\x67\xd2\xa2\xa0\x69\x41\x5f\xf8\xe7\x96\x7f\x23\xab\x00\x03\x5f\x4a\x3c";
FUNC_TYPE_T(w2c_apltyped0x2Egrok_t1) = "\x72\xab\x00\xdf\x20\x3d\xce\xa1\xf2\x29\xc7\x9d\x13\x40\x7e\x98\xac\x7d\x41\x4a\x53\x2e\x42\x42\x61\x55\x2e\xaa\xeb\xbe\xc6\x35";
FUNC_TYPE_T(w2c_apltyped0x2Egrok_t2) = "\xff\x57\x1f\x83\x74\x67\x5d\x67\x2a\xc8\x0d\x92\x3d\xe8\x47\xa1\x1e\x73\xc7\x03\xa1\xee\x83\x72\x66\xa9\x1c\x9d\xe7\x8c\xdd\xfb";
FUNC_TYPE_T(w2c_apltyped0x2Egrok_t3) = "\x92\xfb\x6a\xdf\x49\x07\x0a\x83\xbe\x08\x02\x68\xcd\xf6\x95\x27\x4a\xc2\xf3\xe5\xe4\x7d\x29\x49\xe8\xed\x42\x92\x6a\x9d\xda\xf0";
FUNC_TYPE_T(w2c_apltyped0x2Egrok_t4) = "\x9e\x65\x22\xd4\xaa\xed\xf6\x5d\xec\x27\x81\xe7\xcd\x6b\x8c\x7b\x91\xe0\x27\x79\x1d\xf7\xde\x0d\x07\xa6\xde\xf0\xff\x55\xd8\xca";
FUNC_TYPE_T(w2c_apltyped0x2Egrok_t5) = "\x36\xa9\xe7\xf1\xc9\x5b\x82\xff\xb9\x97\x43\xe0\xc5\xc4\xce\x95\xd8\x3c\x9a\x43\x0a\xac\x59\xf8\x4e\xf3\xcb\xfa\xb6\x14\x50\x68";

static void init_globals(w2c_apltyped0x2Egrok* instance) {
  instance->w2c_g0 = 0u;
  instance->w2c_g1 = 12345u;
}

static void init_memories(w2c_apltyped0x2Egrok* instance) {
  wasm_rt_allocate_memory(&instance->w2c_memory, 2, 65536, 0, 65536);
}

/* export: 'memory' */
wasm_rt_memory_t* w2c_apltyped0x2Egrok_memory(w2c_apltyped0x2Egrok* instance) {
  return &instance->w2c_memory;
}

/* export: 'main' */
struct wasm_multi_iii w2c_apltyped0x2Egrok_main(w2c_apltyped0x2Egrok* instance, u32 var_p0, u32 var_p1) {
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
  struct wasm_multi_iii ret = w2c_apltyped0x2Egrok_main_0(instance, var_p0, var_p1);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
  return ret;
}

/* export: 'reset_heap' */
void w2c_apltyped0x2Egrok_reset_heap(w2c_apltyped0x2Egrok* instance) {
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
  w2c_apltyped0x2Egrok_reset_heap_0(instance);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
}

/* export: 'deal' */
u32 w2c_apltyped0x2Egrok_deal(w2c_apltyped0x2Egrok* instance, u32 var_p0, u32 var_p1) {
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
  u32 ret = w2c_apltyped0x2Egrok_deal_0(instance, var_p0, var_p1);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
  return ret;
}

/* export: 'indexGenerator' */
u32 w2c_apltyped0x2Egrok_indexGenerator(w2c_apltyped0x2Egrok* instance, u32 var_p0) {
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
  u32 ret = w2c_apltyped0x2Egrok_indexGenerator_0(instance, var_p0);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
  return ret;
}

void wasm2c_apltyped0x2Egrok_instantiate(w2c_apltyped0x2Egrok* instance) {
  assert(wasm_rt_is_initialized());
  init_globals(instance);
  init_memories(instance);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
}

void wasm2c_apltyped0x2Egrok_free(w2c_apltyped0x2Egrok* instance) {
  wasm_rt_free_memory(&instance->w2c_memory);
}

wasm_rt_func_type_t wasm2c_apltyped0x2Egrok_get_func_type(uint32_t param_count, uint32_t result_count, ...) {
  va_list args;
  
  if (param_count == 1 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_apltyped0x2Egrok_t0;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_apltyped0x2Egrok_t1;
    }
    va_end(args);
  }
  
  if (param_count == 4 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_apltyped0x2Egrok_t2;
    }
    va_end(args);
  }
  
  if (param_count == 2 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_apltyped0x2Egrok_t3;
    }
    va_end(args);
  }
  
  if (param_count == 2 && result_count == 3) {
    va_start(args, result_count);
    if (true && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32 && va_arg(args, wasm_rt_type_t) == WASM_RT_I32) {
      va_end(args);
      return w2c_apltyped0x2Egrok_t4;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 0) {
    va_start(args, result_count);
    if (true) {
      va_end(args);
      return w2c_apltyped0x2Egrok_t5;
    }
    va_end(args);
  }
  
  return NULL;
}

u32 w2c_apltyped0x2Egrok_f0(w2c_apltyped0x2Egrok* instance, u32 var_p0) {
  u32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g0;
  var_l1 = var_i0;
  var_i0 = instance->w2c_g0;
  var_i1 = var_p0;
  var_i0 += var_i1;
  instance->w2c_g0 = var_i0;
  var_i0 = var_l1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_apltyped0x2Egrok_f1(w2c_apltyped0x2Egrok* instance) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g1;
  var_i1 = 1103515245u;
  var_i0 *= var_i1;
  var_i1 = 12345u;
  var_i0 += var_i1;
  instance->w2c_g1 = var_i0;
  var_i0 = instance->w2c_g1;
  var_i1 = 2147483647u;
  var_i0 &= var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_apltyped0x2Egrok_indexGenerator_0(w2c_apltyped0x2Egrok* instance, u32 var_p0) {
  u32 var_l1 = 0, var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  var_i0 = var_p0;
  var_i1 = 4u;
  var_i0 *= var_i1;
  var_i0 = w2c_apltyped0x2Egrok_f0(instance, var_i0);
  var_l1 = var_i0;
  var_i0 = 0u;
  var_l2 = var_i0;
  var_L1: 
    var_i0 = var_l2;
    var_i1 = var_p0;
    var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
    if (var_i0) {goto var_B0;}
    var_i0 = var_l1;
    var_i1 = var_l2;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i1 = var_l2;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l2;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l2 = var_i0;
    goto var_L1;
  var_B0:;
  var_i0 = var_l1;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_apltyped0x2Egrok_f3(w2c_apltyped0x2Egrok* instance, u32 var_p0, u32 var_p1, u32 var_p2, u32 var_p3) {
  u32 var_l4 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, var_l11 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  var_i0 = var_p3;
  var_i1 = var_p2;
  var_i0 = (u32)((s32)var_i0 <= (s32)var_i1);
  if (var_i0) {
    goto var_Bfunc;
  }
  var_i0 = var_p2;
  var_i1 = var_p3;
  var_i0 += var_i1;
  var_i1 = 2u;
  var_i0 = I32_DIV_S(var_i0, var_i1);
  var_l4 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i2 = var_l4;
  var_i3 = 4u;
  var_i2 *= var_i3;
  var_i1 += var_i2;
  var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
  var_i2 = 4u;
  var_i1 *= var_i2;
  var_i0 += var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l5 = var_i0;
  var_i0 = var_p2;
  var_l8 = var_i0;
  var_i0 = var_p3;
  var_l9 = var_i0;
  var_L2: 
    var_i0 = var_l8;
    var_i1 = var_l9;
    var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
    if (var_i0) {goto var_B1;}
    var_i0 = var_p1;
    var_i1 = var_l8;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l6 = var_i0;
    var_i0 = var_p1;
    var_i1 = var_l9;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l7 = var_i0;
    var_i0 = var_p0;
    var_i1 = var_l6;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_i1 = var_l5;
    var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
    var_l10 = var_i0;
    var_i0 = var_p0;
    var_i1 = var_l7;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_i1 = var_l5;
    var_i0 = (u32)((s32)var_i0 <= (s32)var_i1);
    var_l11 = var_i0;
    var_i0 = var_l10;
    var_i1 = var_l11;
    var_i0 &= var_i1;
    if (var_i0) {
      var_i0 = var_p1;
      var_i1 = var_l8;
      var_i2 = 4u;
      var_i1 *= var_i2;
      var_i0 += var_i1;
      var_i1 = var_l7;
      i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
      var_i0 = var_p1;
      var_i1 = var_l9;
      var_i2 = 4u;
      var_i1 *= var_i2;
      var_i0 += var_i1;
      var_i1 = var_l6;
      i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
      var_i0 = var_l8;
      var_i1 = 1u;
      var_i0 += var_i1;
      var_l8 = var_i0;
      var_i0 = var_l9;
      var_i1 = 1u;
      var_i0 -= var_i1;
      var_l9 = var_i0;
    } else {
      var_i0 = var_l10;
      var_i0 = !(var_i0);
      if (var_i0) {
        var_i0 = var_l8;
        var_i1 = 1u;
        var_i0 += var_i1;
        var_l8 = var_i0;
      }
      var_i0 = var_l11;
      var_i0 = !(var_i0);
      if (var_i0) {
        var_i0 = var_l9;
        var_i1 = 1u;
        var_i0 -= var_i1;
        var_l9 = var_i0;
      }
    }
    goto var_L2;
  var_B1:;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i2 = var_p2;
  var_i3 = var_l9;
  w2c_apltyped0x2Egrok_f3(instance, var_i0, var_i1, var_i2, var_i3);
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i2 = var_l8;
  var_i3 = var_p3;
  w2c_apltyped0x2Egrok_f3(instance, var_i0, var_i1, var_i2, var_i3);
  var_Bfunc:;
  FUNC_EPILOGUE;
}

u32 w2c_apltyped0x2Egrok_deal_0(w2c_apltyped0x2Egrok* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l4 = 0, var_l5 = 0, var_l6 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  var_i0 = var_p0;
  var_i0 = w2c_apltyped0x2Egrok_indexGenerator_0(instance, var_i0);
  var_l2 = var_i0;
  var_i0 = 0u;
  var_l4 = var_i0;
  var_L1: 
    var_i0 = var_l4;
    var_i1 = var_p1;
    var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
    if (var_i0) {goto var_B0;}
    var_i0 = var_l4;
    var_i1 = w2c_apltyped0x2Egrok_f1(instance);
    var_i2 = var_p0;
    var_i3 = var_l4;
    var_i2 -= var_i3;
    var_i1 = I32_REM_S(var_i1, var_i2);
    var_i0 += var_i1;
    var_l5 = var_i0;
    var_i0 = var_l2;
    var_i1 = var_l4;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l6 = var_i0;
    var_i0 = var_l2;
    var_i1 = var_l4;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i1 = var_l2;
    var_i2 = var_l5;
    var_i3 = 4u;
    var_i2 *= var_i3;
    var_i1 += var_i2;
    var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l2;
    var_i1 = var_l5;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i1 = var_l6;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l4;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l4 = var_i0;
    goto var_L1;
  var_B0:;
  var_i0 = var_p1;
  var_i1 = 4u;
  var_i0 *= var_i1;
  var_i0 = w2c_apltyped0x2Egrok_f0(instance, var_i0);
  var_l3 = var_i0;
  var_i0 = 0u;
  var_l4 = var_i0;
  var_L3: 
    var_i0 = var_l4;
    var_i1 = var_p1;
    var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
    if (var_i0) {goto var_B2;}
    var_i0 = var_l3;
    var_i1 = var_l4;
    var_i2 = 4u;
    var_i1 *= var_i2;
    var_i0 += var_i1;
    var_i1 = var_l2;
    var_i2 = var_l4;
    var_i3 = 4u;
    var_i2 *= var_i3;
    var_i1 += var_i2;
    var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l4;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l4 = var_i0;
    goto var_L3;
  var_B2:;
  var_i0 = var_l3;
  FUNC_EPILOGUE;
  return var_i0;
}

struct wasm_multi_iii w2c_apltyped0x2Egrok_main_0(w2c_apltyped0x2Egrok* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l4 = 0, var_l5 = 0, var_l6 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4;
  var_i0 = var_p1;
  var_i1 = var_p1;
  var_i0 = w2c_apltyped0x2Egrok_deal_0(instance, var_i0, var_i1);
  var_l2 = var_i0;
  var_i0 = var_p1;
  var_i0 = w2c_apltyped0x2Egrok_indexGenerator_0(instance, var_i0);
  var_l3 = var_i0;
  var_i0 = 0u;
  var_l4 = var_i0;
  var_L1: 
    var_i0 = var_l4;
    var_i1 = var_p0;
    var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
    if (var_i0) {goto var_B0;}
    var_i0 = var_l2;
    var_i1 = var_l3;
    var_i2 = 0u;
    var_i3 = var_p1;
    var_i4 = 1u;
    var_i3 -= var_i4;
    w2c_apltyped0x2Egrok_f3(instance, var_i0, var_i1, var_i2, var_i3);
    var_i0 = var_l4;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l4 = var_i0;
    goto var_L1;
  var_B0:;
  var_i0 = 1u;
  var_l5 = var_i0;
  var_i0 = 0u;
  var_l6 = var_i0;
  var_L3: 
    var_i0 = var_l6;
    var_i1 = var_p1;
    var_i0 = (u32)((s32)var_i0 >= (s32)var_i1);
    if (var_i0) {goto var_B2;}
    var_i0 = var_l5;
    var_i1 = var_l2;
    var_i2 = var_l3;
    var_i3 = var_l6;
    var_i4 = 4u;
    var_i3 *= var_i4;
    var_i2 += var_i3;
    var_i2 = i32_load_default32(&instance->w2c_memory, (u64)(var_i2));
    var_i3 = 4u;
    var_i2 *= var_i3;
    var_i1 += var_i2;
    var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
    var_i2 = var_l6;
    var_i1 = var_i1 == var_i2;
    var_i0 &= var_i1;
    var_l5 = var_i0;
    var_i0 = var_l6;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l6 = var_i0;
    goto var_L3;
  var_B2:;
  var_i0 = var_l3;
  var_i1 = var_l2;
  var_i2 = var_l5;
  FUNC_EPILOGUE;
  {
    struct wasm_multi_iii tmp;
    tmp.i0 = var_i0;
    tmp.i1 = var_i1;
    tmp.i2 = var_i2;
    return tmp;
  }
}

void w2c_apltyped0x2Egrok_reset_heap_0(w2c_apltyped0x2Egrok* instance) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = 0u;
  instance->w2c_g0 = var_i0;
  FUNC_EPILOGUE;
}
